export const isNumber = (value: string): boolean => /^[0-9]$/.test(value)
export const isZero = (value: string): boolean => /^0$/.test(value)
export const isOperator = (value: string): boolean => /^[+\-*=/]$/.test(value)
export const isEqualOperator = (value: string): boolean => /^=$/.test(value)
export const isMinusOperator = (value: string): boolean => /^-$/.test(value)
export const isDot = (value: string): boolean => /^\.$/.test(value)
export const isEmptyString = (value: string): boolean => value.length === 0
export const isStringOfNumbers = (value: string): boolean => /^-?[0-9]+$/.test(value)
export const isStringOfNumbersEndsWithDot = (value: string): boolean => /^-?[0-9]+\.$/.test(value)
export const isStringOfNumbersWithDotInTheMiddle = (value: string): boolean => /^-?[0-9]+\.[0-9]+$/.test(value)
